Unsupported operator aten::max_pool2d encountered 3 time(s)
[32m[2025-03-18 00:20:25 alexnet][0m[33m(main.py 74)[0m: INFO AlexNet(
  #params: 57.82M, #flops: 95.59M
  (features): Sequential(
    #params: 2.47M, #flops: 40.24M
    (0): Conv2d(
      3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2)
      #params: 23.3K, #flops: 5.95M
    )
    (1): ReLU()
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(
      64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2)
      #params: 0.31M, #flops: 15.05M
    )
    (4): ReLU()
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(
      192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
      #params: 0.66M, #flops: 5.97M
    )
    (7): ReLU()
    (8): Conv2d(
      384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
      #params: 0.88M, #flops: 7.96M
    )
    (9): ReLU()
    (10): Conv2d(
      256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
      #params: 0.59M, #flops: 5.31M
    )
    (11): ReLU()
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (13): AdaptiveAvgPool2d(
      output_size=(6, 6)
      #params: 0, #flops: 0.26K
    )
  )
  (classifier): Sequential(
    #params: 55.35M, #flops: 55.35M
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(
      in_features=9216, out_features=4096, bias=True
      #params: 37.75M, #flops: 37.75M
    )
    (2): ReLU()
    (3): Dropout(p=0.5, inplace=False)
    (4): Linear(
      in_features=4096, out_features=4096, bias=True
      #params: 16.78M, #flops: 16.78M
    )
    (5): ReLU()
    (6): Linear(
      in_features=4096, out_features=200, bias=True
      #params: 0.82M, #flops: 0.82M
    )
  )
)
[32m[2025-03-18 00:20:25 alexnet][0m[33m(main.py 75)[0m: INFO number of params: 57.82324 M
[32m[2025-03-18 00:20:25 alexnet][0m[33m(main.py 76)[0m: INFO flops: 95.588608 MFLOPS
[32m[2025-03-18 00:20:25 alexnet][0m[33m(main.py 92)[0m: INFO Start training
Traceback (most recent call last):                                                                                        
[32m[2025-03-18 00:33:09 alexnet][0m[33m(main.py 161)[0m: INFO Train: [0/50]	lr 0.000300	time 0.0240 (0.0153)	loss 2.3073 (2.3071)	Acc@1 0.000 (10.188)	Mem 1121MB
[32m[2025-03-18 00:33:09 alexnet][0m[33m(main.py 170)[0m: INFO EPOCH 0 training takes 0:12:44
[32m[2025-03-18 00:33:09 alexnet][0m[33m(main.py 96)[0m: INFO  * Train Acc 10.188 Train Loss 2.307
[32m[2025-03-18 00:33:09 alexnet][0m[33m(main.py 97)[0m: INFO Accuracy of the network on the 50000 train images: 10.2%
[32m[2025-03-18 00:33:36 alexnet][0m[33m(main.py 209)[0m: INFO Validate: 	Time 0.002 (0.003)	Loss 2.2941 (2.3028)	Acc@1 0.000 (10.000)	Mem 1121MB
[32m[2025-03-18 00:33:36 alexnet][0m[33m(main.py 101)[0m: INFO  * Val Acc 10.000 Val Loss 2.303
[32m[2025-03-18 00:33:36 alexnet][0m[33m(main.py 102)[0m: INFO Accuracy of the network on the 10000 val images: 10.0%
[32m[2025-03-18 00:33:36 alexnet][0m[33m(load_save.py 48)[0m: INFO output/alexnet/ckpt_best.pth saving......
[32m[2025-03-18 00:33:41 alexnet][0m[33m(load_save.py 50)[0m: INFO output/alexnet/ckpt_best.pth saved !!!
[32m[2025-03-18 00:33:41 alexnet][0m[33m(main.py 108)[0m: INFO Max accuracy: 10.00%
  File "/home/jaansi/fa24-nmep-hw2/main.py", line 259, in <module>
    main(config)
  File "/home/jaansi/fa24-nmep-hw2/main.py", line 113, in main
    "val_acc": val_acc1, "val_loss": val_loss, "throughput": config.TRAIN.BATCH_SIZE/epoch_time}
                                                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaansi/miniconda3/lib/python3.12/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: BATCH_SIZE
